import type { DfidClientConfig } from './types.js';
import { projectHeaders } from './hmac.js';
import type { paths } from './generated/openapi-types.js';

// Per-app sessions — "your sessions in this app" panels on satellites.
//
// Both methods are server-only and project-HMAC authed (X-DFF-Project +
// X-DFF-Signature, same scheme as profile.getUser / entitlements.pull). The
// hub scopes everything to the calling project structurally: a session row
// must carry the caller's oauth_client_id, so a satellite can only ever see
// or revoke its OWN sessions — never a hub session or another app's.
//
// Types come from the hub's OpenAPI spec (src/generated/openapi-types.ts,
// regenerated by `npm run openapi:types` in the hub repo) — the SDK can't
// drift from the published contract.

type SessionsListResponse =
    paths['/api/sessions']['get']['responses']['200']['content']['application/json'];
type SessionRevokeResponse =
    paths['/api/sessions/{id}']['delete']['responses']['200']['content']['application/json'];

/**
 * One of the calling app's sessions for a user, as returned by
 * `GET /api/sessions?user_id=…`. Device fields are parsed from the session's
 * user-agent; location comes from the hub's geo side table and is null for
 * sessions minted server-to-server (render "Unknown").
 */
export type AppSession = SessionsListResponse['sessions'][number];

/**
 * A recent auth event (sign-in, refresh, revocation, …) attributable to the
 * calling project, returned alongside the live sessions by `sessions.list`.
 */
export type AppAuthEvent = SessionsListResponse['recent_events'][number];

export type SessionsListResult = SessionsListResponse;

export function createSessions(config: DfidClientConfig) {
    return {
        /**
         * List the calling app's live sessions (plus recent auth events) for
         * `userId`. The signed payload is the literal user_id string (same
         * convention as `profile.getUser`). Subject to the consent gate — a
         * user who revoked the app from their connected-apps panel gets 403.
         * GET /api/sessions?user_id=<uuid>.
         */
        async list({ userId }: { userId: string }): Promise<SessionsListResult> {
            const headers = projectHeaders(config.projectId, config.hmacSecret, userId);
            const res = await fetch(
                `${config.url}/api/sessions?user_id=${encodeURIComponent(userId)}`,
                { headers },
            );
            if (!res.ok) {
                const err = (await res.json().catch(() => null)) as { error?: string } | null;
                throw new Error(err?.error ?? `sessions.list failed: ${res.status}`);
            }
            return (await res.json()) as SessionsListResult;
        },

        /**
         * Revoke ONE of the calling app's sessions ("sign out this device").
         * The signed payload is the literal session id. Scope is structural —
         * the session must belong to this app's OAuth client, so revoking a
         * hub session or another app's session 404s.
         * DELETE /api/sessions/:id.
         */
        async revoke({
            sessionId,
        }: {
            sessionId: string;
        }): Promise<{ revoked: boolean; sessionId: string }> {
            const headers = projectHeaders(config.projectId, config.hmacSecret, sessionId);
            const res = await fetch(
                `${config.url}/api/sessions/${encodeURIComponent(sessionId)}`,
                { method: 'DELETE', headers },
            );
            if (!res.ok) {
                const err = (await res.json().catch(() => null)) as { error?: string } | null;
                throw new Error(err?.error ?? `sessions.revoke failed: ${res.status}`);
            }
            const json = (await res.json()) as SessionRevokeResponse;
            return { revoked: json.revoked, sessionId: json.session_id };
        },
    };
}
